#!/bin/bash

# RevenueCat MCP Configuration Script
# This script provides MCP commands to configure RevenueCat

echo "🚀 RevenueCat MCP Configuration"
echo "================================"
echo ""
echo "⚠️  IMPORTANT: Make sure Cursor is restarted after setting up mcp.json"
echo ""
echo "📋 MCP Commands to run in Cursor:"
echo ""
echo "1. Check project details:"
echo "   Show me my RevenueCat project details"
echo ""
echo "2. Create Premium Entitlement:"
echo "   Create an entitlement with identifier \"premium\", display name \"Premium Membership\", and description \"Unlimited AI image generation and premium features\""
echo ""
echo "3. Create Monthly Product:"
echo "   Create a monthly subscription product with identifier \"com.someplanets.monzieaiv2.monthly\" for iOS platform"
echo ""
echo "4. Create Yearly Product:"
echo "   Create an annual subscription product with identifier \"com.someplanets.monzieaiv2.yearly\" for iOS platform"
echo ""
echo "5. Create Monthly Package:"
echo "   Create a package with identifier \"\$rc_monthly\" that includes product \"com.someplanets.monzieaiv2.monthly\" and grants entitlement \"premium\""
echo ""
echo "6. Create Annual Package:"
echo "   Create a package with identifier \"\$rc_annual\" that includes product \"com.someplanets.monzieaiv2.yearly\" and grants entitlement \"premium\""
echo ""
echo "7. Create Default Offering:"
echo "   Create an offering with identifier \"default\", display name \"Premium Plans\", and include packages \"\$rc_monthly\" and \"\$rc_annual\""
echo ""
echo "8. Verify Configuration:"
echo "   List all my products"
echo "   List all my entitlements"
echo "   List all my offerings"
echo "   Show me the default offering details"
echo ""
echo "✅ After completing these steps, update app.json with iOS API Key"
echo ""

